"""Composable Bayesian SED fitting and photo-z inference."""

from importlib.metadata import PackageNotFoundError, version

from composed.data import SEDDataset, SpectroPhotometricDataset, SpectrumDataset
from composed.derived import DerivedSFHQuantities, derive_sfh_quantities
from composed.diagnostics import DiagnosticReport, diagnose
from composed.errors import ModelDomainError
from composed.catalog import CatalogGridResult, run_photometric_grid_catalog
from composed.catalog_fast import (
    NativeCatalogFitResult,
    RedshiftFilterOperator,
    RestFrameSpectralGrid,
    build_redshift_filter_operator,
    build_restframe_spectral_grid,
    fit_catalog_with_restframe_grid,
    load_restframe_spectral_grid,
    project_rest_grid_to_photometric_grid,
    save_restframe_spectral_grid,
)
from composed.likelihood import GaussianPhotometricLikelihood, GaussianSpectralLikelihood
from composed.filters import FilterSet, load_filter_set
from composed.parameters import ParameterSpace
from composed.noise import ConditionalCatalogNoise, EmpiricalPhotometricNoise
from composed.priors import (
    ChoicePrior,
    DeltaPrior,
    IntegerUniformPrior,
    LogUniformPrior,
    NormalPrior,
    StudentTPrior,
    UniformPrior,
)
from composed.problem import (
    Emcee,
    Gaussian,
    Grid,
    Laplace,
    MixedGibbs,
    MixedTAMIS,
    PocoMC,
    Problem,
    RandomWalk,
    Sampler,
    SamplerCapabilities,
    TAMIS,
    fit,
)
from composed.provenance import (
    collect_run_provenance,
    provenance_path_for,
    read_provenance,
    require_provenance,
    save_npz_with_provenance,
    sha256_file,
    verify_artifact_provenance,
    write_provenance,
)
from composed.results import (
    InferenceResult,
    InferenceFailure,
    load_inference_result,
    normalize_sampling_result,
    posterior_summary,
    problem_fingerprint,
    require_result_matches_problem,
    save_inference_result,
)
from composed.sbi import (
    MAF,
    MAFCatalogSummary,
    MAFPhotometricSBIResult,
    MDN,
    MDNPhotometricSBIResult,
    PhotometricContext,
    PhotometricTrainingSet,
    SBIContextSupportWarning,
    SBIPosteriorSaturationWarning,
    SBISimulationFailureWarning,
    SBITrainingSet,
    Simulate,
    TrainedMAFSBI,
    TrainedMDNSBI,
    simulate_photometric_training_set,
    simulate_sbi_training_set,
    train_sbi,
    train_maf_photometric_sbi,
    train_mdn_photometric_sbi,
    transform_photometry,
)
from composed.sfh import (
    ConstantSFH,
    ContinuitySFH,
    DelayedTauSFH,
    ExponentialSFH,
    SFHHistory,
    SFHModel,
    TabularSFH,
    available_sfh_models,
    make_sfh,
)
from composed.units import MassNormalization, MassReference

try:
    __version__ = version("composed-sed")
except PackageNotFoundError:
    __version__ = "0+unknown"

__all__ = [
    "__version__",
    "ConstantSFH",
    "ContinuitySFH",
    "DelayedTauSFH",
    "DiagnosticReport",
    "ExponentialSFH",
    "SFHHistory",
    "SFHModel",
    "TabularSFH",
    "available_sfh_models",
    "make_sfh",
    "ChoicePrior",
    "DeltaPrior",
    "DerivedSFHQuantities",
    "CatalogGridResult",
    "GaussianPhotometricLikelihood",
    "GaussianSpectralLikelihood",
    "Gaussian",
    "Grid",
    "InferenceResult",
    "InferenceFailure",
    "IntegerUniformPrior",
    "Laplace",
    "FilterSet",
    "LogUniformPrior",
    "MassNormalization",
    "MassReference",
    "ModelDomainError",
    "MAF",
    "MAFCatalogSummary",
    "MAFPhotometricSBIResult",
    "MDN",
    "MDNPhotometricSBIResult",
    "PhotometricContext",
    "MixedGibbs",
    "MixedTAMIS",
    "NormalPrior",
    "StudentTPrior",
    "NativeCatalogFitResult",
    "ParameterSpace",
    "PocoMC",
    "Problem",
    "PhotometricTrainingSet",
    "SBIContextSupportWarning",
    "SBIPosteriorSaturationWarning",
    "SBISimulationFailureWarning",
    "SBITrainingSet",
    "RedshiftFilterOperator",
    "RestFrameSpectralGrid",
    "SEDDataset",
    "Sampler",
    "SamplerCapabilities",
    "Simulate",
    "SpectroPhotometricDataset",
    "SpectrumDataset",
    "RandomWalk",
    "TAMIS",
    "TrainedMAFSBI",
    "TrainedMDNSBI",
    "Emcee",
    "ConditionalCatalogNoise",
    "EmpiricalPhotometricNoise",
    "UniformPrior",
    "build_redshift_filter_operator",
    "build_restframe_spectral_grid",
    "collect_run_provenance",
    "fit_catalog_with_restframe_grid",
    "derive_sfh_quantities",
    "diagnose",
    "fit",
    "load_restframe_spectral_grid",
    "load_inference_result",
    "load_filter_set",
    "normalize_sampling_result",
    "posterior_summary",
    "problem_fingerprint",
    "project_rest_grid_to_photometric_grid",
    "provenance_path_for",
    "read_provenance",
    "require_provenance",
    "require_result_matches_problem",
    "run_photometric_grid_catalog",
    "simulate_photometric_training_set",
    "simulate_sbi_training_set",
    "save_inference_result",
    "save_npz_with_provenance",
    "save_restframe_spectral_grid",
    "sha256_file",
    "verify_artifact_provenance",
    "train_maf_photometric_sbi",
    "train_mdn_photometric_sbi",
    "train_sbi",
    "transform_photometry",
    "write_provenance",
]
