"""Nonlinear toy-SED validation for experimental diffusion SBI.

This is the second validation rung after the analytic Gaussian conditional
test.  The simulator is still intentionally simple and fast, but it has the
shape of an SED problem:

    theta = [redshift, log10_mass, dust2, logzsol]
    x     = [u, g, r, i, z, Y, J, H magnitudes, theta]

The photometry is generated by a deterministic nonlinear toy SED plus Gaussian
mag noise.  Because the prior and noise model are explicit, we can compare the
diffusion posterior against a brute-force Monte Carlo reference posterior.

This is not a physical FSPS/CIGALE validation.  It checks whether masked
diffusion can learn SED-like nonlinear inverse, forward, and missing-band
conditionals before expensive backend physics enters the loop.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
import sys
import time

import numpy as np

os.environ.setdefault("MPLCONFIGDIR", "/tmp/composed_mplconfig")

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from inftools.diagnostics import marginal_coverage, rank_statistics
from inftools.experimental.diffusion import ConditionalDiffusionEstimator, FeatureMetadata


BAND_NAMES = ["u", "g", "r", "i", "z", "Y", "J", "H"]
BAND_WAVELENGTH_UM = np.array([0.36, 0.48, 0.62, 0.76, 0.90, 1.05, 1.25, 1.65])
PARAM_NAMES = ["redshift", "log10_mass", "dust2", "logzsol"]
PARAM_LOW = np.array([0.0, 8.0, 0.0, -1.2])
PARAM_HIGH = np.array([3.0, 12.0, 1.2, 0.3])
# This deliberately uses broad toy magnitude errors.  The purpose is to test
# the masked joint sampler against a brute-force reference posterior without
# making the validation dominated by a few extremely sharp nearest-neighbour
# points in the reference prior bank.
MAG_SIGMA = np.array([0.32, 0.28, 0.25, 0.23, 0.23, 0.25, 0.28, 0.32])


def sample_prior(rng: np.random.Generator, n: int) -> np.ndarray:
    """Draw toy physical parameters from independent uniform priors."""

    unit = rng.uniform(0.0, 1.0, size=(int(n), PARAM_LOW.size))
    return PARAM_LOW + unit * (PARAM_HIGH - PARAM_LOW)


def toy_noiseless_magnitudes(theta: np.ndarray) -> np.ndarray:
    """Return nonlinear toy observed magnitudes for ``theta``.

    Parameters are ordered as ``[redshift, log10_mass, dust2, logzsol]``.
    The model includes mass brightening, redshift dimming, a 4000 Angstrom-like
    break, a Lyman-like blue dropout, smooth dust reddening, metallicity color,
    and broad emission-line bumps.  The constants are chosen for diagnostic
    structure, not physical calibration.
    """

    theta = np.asarray(theta, dtype=float)
    if theta.ndim == 1:
        theta = theta[None, :]
    z = theta[:, 0:1]
    log10_mass = theta[:, 1:2]
    dust2 = theta[:, 2:3]
    logzsol = theta[:, 3:4]

    obs_um = BAND_WAVELENGTH_UM.reshape(1, -1)
    rest_um = obs_um / (1.0 + z)
    log_rest = np.log(rest_um / 0.55)

    mass_term = 23.4 - 2.35 * (log10_mass - 10.0)
    distance_like = 2.2 * np.log1p(z) + 0.8 * z
    continuum_color = 0.55 * log_rest + 0.18 * np.sin(2.5 * log_rest + 0.6 * z)
    dust_attenuation = 1.15 * dust2 * np.power(np.maximum(rest_um, 0.09) / 0.55, -0.75)

    break_strength = 0.45 + 0.35 * (logzsol + 0.6) + 0.20 * dust2
    blue_side_of_break = 1.0 / (1.0 + np.exp((rest_um - 0.40) / 0.035))
    break_term = break_strength * blue_side_of_break

    lyman_drop = 2.8 * (1.0 + 0.2 * z) / (1.0 + np.exp((rest_um - 0.1216) / 0.015))
    metallicity_color = 0.25 * logzsol * np.tanh((rest_um - 0.65) / 0.25)

    line_strength = (0.45 + 0.25 * np.tanh(log10_mass - 10.0)) * np.exp(-1.4 * dust2)
    line_term = np.zeros_like(rest_um)
    for line_um, amplitude, width_um in [(0.3727, 0.55, 0.035), (0.5007, 0.75, 0.045), (0.6563, 0.65, 0.055)]:
        line_term -= amplitude * line_strength * np.exp(-0.5 * ((rest_um - line_um) / width_um) ** 2)

    mags = mass_term + distance_like + continuum_color + dust_attenuation + break_term + lyman_drop + metallicity_color + line_term
    return np.asarray(mags, dtype=float)


def simulate_observed_magnitudes(theta: np.ndarray, rng: np.random.Generator) -> np.ndarray:
    noiseless = toy_noiseless_magnitudes(theta)
    return noiseless + rng.normal(0.0, MAG_SIGMA.reshape(1, -1), size=noiseless.shape)


def make_training_table(rng: np.random.Generator, n: int) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    theta = sample_prior(rng, n)
    mags = simulate_observed_magnitudes(theta, rng)
    return np.column_stack([mags, theta]), mags, theta


def log_mag_likelihood(observed_mags: np.ndarray, model_mags: np.ndarray, band_index: np.ndarray) -> np.ndarray:
    """Diagonal Gaussian magnitude likelihood up to an additive constant."""

    residual = (observed_mags[band_index] - model_mags[:, band_index]) / MAG_SIGMA[band_index]
    return -0.5 * np.sum(residual**2, axis=1)


def weighted_resample(
    values: np.ndarray,
    log_weight: np.ndarray,
    rng: np.random.Generator,
    n_samples: int,
) -> tuple[np.ndarray, np.ndarray, float]:
    """Resample rows from log weights and return effective sample size."""

    log_weight = np.asarray(log_weight, dtype=float)
    finite = np.isfinite(log_weight)
    if not np.any(finite):
        raise RuntimeError("All reference posterior log weights are non-finite.")
    shifted = log_weight - np.max(log_weight[finite])
    weight = np.exp(shifted)
    weight[~finite] = 0.0
    weight_sum = np.sum(weight)
    if weight_sum <= 0.0:
        raise RuntimeError("All reference posterior weights are zero.")
    probability = weight / weight_sum
    ess = 1.0 / np.sum(probability**2)
    index = rng.choice(values.shape[0], size=int(n_samples), replace=True, p=probability)
    return values[index], probability, float(ess)


def reference_inverse_samples(
    observed_mags: np.ndarray,
    reference_theta: np.ndarray,
    reference_mags_noiseless: np.ndarray,
    rng: np.random.Generator,
    *,
    n_samples: int,
    band_index: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Brute-force prior-bank posterior samples for theta | observed bands."""

    samples = []
    ess_values = []
    for row in range(observed_mags.shape[0]):
        logw = log_mag_likelihood(observed_mags[row], reference_mags_noiseless, band_index)
        ref, _, ess = weighted_resample(reference_theta, logw, rng, n_samples)
        samples.append(ref)
        ess_values.append(ess)
    return np.asarray(samples), np.asarray(ess_values)


def reference_mixed_samples(
    observed_mags: np.ndarray,
    reference_theta: np.ndarray,
    reference_mags_noiseless: np.ndarray,
    rng: np.random.Generator,
    *,
    n_samples: int,
    known_band_index: np.ndarray,
    missing_band_index: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Reference samples for [missing mags, theta] | known observed mags."""

    samples = []
    ess_values = []
    for row in range(observed_mags.shape[0]):
        logw = log_mag_likelihood(observed_mags[row], reference_mags_noiseless, known_band_index)
        theta_samples, probability, ess = weighted_resample(reference_theta, logw, rng, n_samples)
        chosen = rng.choice(reference_theta.shape[0], size=n_samples, replace=True, p=probability)
        missing_mean = reference_mags_noiseless[chosen][:, missing_band_index]
        missing_mags = missing_mean + rng.normal(0.0, MAG_SIGMA[missing_band_index], size=missing_mean.shape)
        samples.append(np.column_stack([missing_mags, theta_samples]))
        ess_values.append(ess)
    return np.asarray(samples), np.asarray(ess_values)


def sample_diffusion_case(
    estimator: ConditionalDiffusionEstimator,
    x_test: np.ndarray,
    known_index: np.ndarray,
    *,
    num_samples: int,
    steps: int,
) -> tuple[np.ndarray, float, float]:
    """Sample the diffusion conditional and return samples, seconds, clamp error."""

    known_index = np.asarray(known_index, dtype=int)
    mask = np.zeros_like(x_test, dtype=bool)
    mask[:, known_index] = True
    known = np.full_like(x_test, np.nan)
    known[:, known_index] = x_test[:, known_index]
    t0 = time.perf_counter()
    samples = estimator.sample(
        known,
        mask,
        num_samples=num_samples,
        steps=steps,
        sampler="edm_euler",
        batch_size=min(64, x_test.shape[0]),
    )
    seconds = time.perf_counter() - t0
    clamp_error = float(np.max(np.abs(samples[:, :, known_index] - x_test[:, None, known_index])))
    return samples, seconds, clamp_error


def compare_sample_cubes(diffusion_samples: np.ndarray, reference_samples: np.ndarray, truth: np.ndarray) -> dict:
    """Compare diffusion samples to reference samples and generating truth."""

    diff_mean = np.mean(diffusion_samples, axis=1)
    ref_mean = np.mean(reference_samples, axis=1)
    diff_std = np.std(diffusion_samples, axis=1)
    ref_std = np.std(reference_samples, axis=1)
    median = np.median(diffusion_samples, axis=1)
    normalized_mean_abs_error = np.mean(np.abs(diff_mean - ref_mean) / np.maximum(ref_std, 1e-6), axis=0)
    std_relative_error = np.mean(np.abs(diff_std - ref_std) / np.maximum(ref_std, 1e-6), axis=0)
    truth_rmse = np.sqrt(np.mean((median - truth) ** 2, axis=0))
    coverage_68 = central_interval_coverage(diffusion_samples, truth, level=0.68)
    ranks = rank_statistics(diffusion_samples, truth)
    coverage_curve = marginal_coverage(diffusion_samples, truth, levels=np.array([0.5, 0.68, 0.9]))
    return {
        "diffusion_mean": diff_mean,
        "reference_mean": ref_mean,
        "diffusion_std": diff_std,
        "reference_std": ref_std,
        "normalized_mean_abs_error": normalized_mean_abs_error,
        "std_relative_error": std_relative_error,
        "truth_rmse": truth_rmse,
        "coverage_68": coverage_68,
        "rank_percentiles": ranks["rank_percentiles"],
        "coverage_curve": coverage_curve,
    }


def central_interval_coverage(samples: np.ndarray, truth: np.ndarray, level: float = 0.68) -> np.ndarray:
    low_q = 0.5 * (1.0 - level)
    high_q = 1.0 - low_q
    lo = np.quantile(samples, low_q, axis=1)
    hi = np.quantile(samples, high_q, axis=1)
    return np.mean((truth >= lo) & (truth <= hi), axis=0)


def evaluate_forward_mags_given_theta(
    estimator: ConditionalDiffusionEstimator,
    x_test: np.ndarray,
    theta_test: np.ndarray,
    *,
    num_samples: int,
    steps: int,
) -> dict:
    """Evaluate sampled noisy magnitudes against exact p(mags | theta)."""

    known_index = np.arange(len(BAND_NAMES), len(BAND_NAMES) + len(PARAM_NAMES))
    samples, seconds, clamp_error = sample_diffusion_case(estimator, x_test, known_index, num_samples=num_samples, steps=steps)
    mag_samples = samples[:, :, : len(BAND_NAMES)]
    exact_mean = toy_noiseless_magnitudes(theta_test)
    exact_std = np.broadcast_to(MAG_SIGMA.reshape(1, -1), exact_mean.shape)
    sample_mean = np.mean(mag_samples, axis=1)
    sample_std = np.std(mag_samples, axis=1)
    return {
        "samples": mag_samples,
        "seconds": seconds,
        "known_max_abs_error": clamp_error,
        "mean_rmse": float(np.sqrt(np.mean((sample_mean - exact_mean) ** 2))),
        "std_relative_error": float(np.mean(np.abs(sample_std - exact_std) / exact_std)),
        "sample_mean": sample_mean,
        "exact_mean": exact_mean,
        "sample_std": sample_std,
        "exact_std": exact_std,
    }


def plot_training_loss(history: dict, output_dir: Path) -> None:
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(5.0, 3.5))
    ax.plot(history["train_loss"], color="C0")
    ax.set_xlabel("epoch")
    ax.set_ylabel("diffusion score loss")
    ax.set_title("Toy SED diffusion training loss")
    fig.tight_layout()
    fig.savefig(output_dir / "training_loss.png", dpi=160)
    plt.close(fig)


def plot_inverse_summary(comparison: dict, output_dir: Path) -> None:
    import matplotlib.pyplot as plt

    names = PARAM_NAMES
    fig, axes = plt.subplots(1, 3, figsize=(13.5, 3.8))

    ax = axes[0]
    for j, name in enumerate(names):
        ax.scatter(comparison["reference_mean"][:, j], comparison["diffusion_mean"][:, j], s=15, alpha=0.65, label=name)
    lo = min(float(np.min(comparison["reference_mean"])), float(np.min(comparison["diffusion_mean"])))
    hi = max(float(np.max(comparison["reference_mean"])), float(np.max(comparison["diffusion_mean"])))
    ax.plot([lo, hi], [lo, hi], color="0.4", ls="--")
    ax.set_xlabel("MC reference posterior mean")
    ax.set_ylabel("diffusion posterior mean")
    ax.set_title("theta | all mags")
    ax.legend(fontsize=8)

    ax = axes[1]
    for j, name in enumerate(names):
        ax.hist(comparison["rank_percentiles"][:, j], bins=np.linspace(0.0, 1.0, 11), alpha=0.45, label=name)
    ax.set_xlabel("rank percentile of generating truth")
    ax.set_ylabel("count")
    ax.set_title("rank histogram")
    ax.legend(fontsize=8)

    ax = axes[2]
    curve = comparison["coverage_curve"]
    ax.plot([0.0, 1.0], [0.0, 1.0], color="0.4", ls="--", label="ideal")
    for j, name in enumerate(names):
        ax.plot(curve["levels"], curve["coverage"][:, j], marker="o", label=name)
    ax.set_xlabel("central credible level")
    ax.set_ylabel("empirical coverage")
    ax.set_xlim(0.0, 1.0)
    ax.set_ylim(0.0, 1.0)
    ax.set_title("coverage")
    ax.legend(fontsize=8)

    fig.tight_layout()
    fig.savefig(output_dir / "inverse_theta_given_mags_summary.png", dpi=160)
    plt.close(fig)


def plot_forward_summary(forward: dict, output_dir: Path) -> None:
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, 2, figsize=(10.0, 3.8))
    axes[0].scatter(forward["exact_mean"].reshape(-1), forward["sample_mean"].reshape(-1), s=12, alpha=0.65)
    lo = min(float(np.min(forward["exact_mean"])), float(np.min(forward["sample_mean"])))
    hi = max(float(np.max(forward["exact_mean"])), float(np.max(forward["sample_mean"])))
    axes[0].plot([lo, hi], [lo, hi], color="0.4", ls="--")
    axes[0].set_xlabel("exact noisy-mag mean")
    axes[0].set_ylabel("diffusion sample mean")
    axes[0].set_title("mags | theta mean")

    ratio = forward["sample_std"] / forward["exact_std"]
    axes[1].boxplot([ratio[:, j] for j in range(len(BAND_NAMES))], tick_labels=BAND_NAMES)
    axes[1].axhline(1.0, color="0.4", ls="--")
    axes[1].set_ylabel("sample std / exact sigma")
    axes[1].set_title("mags | theta width")
    fig.tight_layout()
    fig.savefig(output_dir / "forward_mags_given_theta_summary.png", dpi=160)
    plt.close(fig)


def plot_mixed_summary(comparison: dict, unknown_names: list[str], output_dir: Path) -> None:
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, 2, figsize=(10.0, 3.8))
    axes[0].scatter(comparison["reference_mean"].reshape(-1), comparison["diffusion_mean"].reshape(-1), s=12, alpha=0.65)
    lo = min(float(np.min(comparison["reference_mean"])), float(np.min(comparison["diffusion_mean"])))
    hi = max(float(np.max(comparison["reference_mean"])), float(np.max(comparison["diffusion_mean"])))
    axes[0].plot([lo, hi], [lo, hi], color="0.4", ls="--")
    axes[0].set_xlabel("MC reference mean")
    axes[0].set_ylabel("diffusion mean")
    axes[0].set_title("mixed missing-band mean")

    values = comparison["normalized_mean_abs_error"]
    axes[1].bar(np.arange(len(values)), values)
    axes[1].set_xticks(np.arange(len(values)), unknown_names, rotation=35, ha="right")
    axes[1].set_ylabel("|mean error| / reference std")
    axes[1].set_title("normalized mean error")
    fig.tight_layout()
    fig.savefig(output_dir / "mixed_missing_band_summary.png", dpi=160)
    plt.close(fig)


def plot_toy_sed_example(
    observed_mags: np.ndarray,
    theta: np.ndarray,
    inverse_samples: np.ndarray,
    output_dir: Path,
) -> None:
    import matplotlib.pyplot as plt

    true_noiseless = toy_noiseless_magnitudes(theta[None, :])[0]
    posterior_theta = inverse_samples[0]
    idx = np.linspace(0, posterior_theta.shape[0] - 1, min(80, posterior_theta.shape[0]), dtype=int)
    posterior_mags = toy_noiseless_magnitudes(posterior_theta[idx])
    q16, q50, q84 = np.quantile(posterior_mags, [0.16, 0.5, 0.84], axis=0)

    fig, ax = plt.subplots(figsize=(7.0, 4.2))
    ax.errorbar(BAND_WAVELENGTH_UM, observed_mags, yerr=MAG_SIGMA, fmt="o", color="k", label="observed noisy mags")
    ax.plot(BAND_WAVELENGTH_UM, true_noiseless, color="C0", lw=2, label="true noiseless toy SED")
    ax.plot(BAND_WAVELENGTH_UM, q50, color="C3", lw=2, label="diffusion posterior median SED")
    ax.fill_between(BAND_WAVELENGTH_UM, q16, q84, color="C3", alpha=0.22, label="16-84%")
    ax.invert_yaxis()
    ax.set_xscale("log")
    ax.set_xticks(BAND_WAVELENGTH_UM, BAND_NAMES)
    ax.set_xlabel("observed band")
    ax.set_ylabel("magnitude")
    ax.set_title("Toy SED posterior predictive example")
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(output_dir / "toy_sed_posterior_predictive_example.png", dpi=160)
    plt.close(fig)


def serializable_metrics(
    *,
    history: dict,
    device: str,
    inverse: dict,
    forward: dict,
    mixed: dict,
    inverse_ess: np.ndarray,
    mixed_ess: np.ndarray,
    mixed_unknown_names: list[str],
) -> dict:
    return {
        "device": str(device),
        "final_train_loss": float(history["train_loss"][-1]),
        "n_epochs": int(len(history["train_loss"])),
        "inverse_theta_given_all_mags": {
            "unknown_features": PARAM_NAMES,
            "reference_ess_median": float(np.median(inverse_ess)),
            "reference_ess_min": float(np.min(inverse_ess)),
            "normalized_mean_abs_error": {
                name: float(value) for name, value in zip(PARAM_NAMES, inverse["normalized_mean_abs_error"])
            },
            "std_relative_error": {
                name: float(value) for name, value in zip(PARAM_NAMES, inverse["std_relative_error"])
            },
            "truth_rmse": {name: float(value) for name, value in zip(PARAM_NAMES, inverse["truth_rmse"])},
            "coverage_68": {name: float(value) for name, value in zip(PARAM_NAMES, inverse["coverage_68"])},
        },
        "forward_mags_given_theta": {
            "mean_rmse_mag": float(forward["mean_rmse"]),
            "std_relative_error": float(forward["std_relative_error"]),
            "known_max_abs_error": float(forward["known_max_abs_error"]),
            "seconds": float(forward["seconds"]),
        },
        "mixed_missing_red_bands": {
            "unknown_features": mixed_unknown_names,
            "reference_ess_median": float(np.median(mixed_ess)),
            "reference_ess_min": float(np.min(mixed_ess)),
            "normalized_mean_abs_error": {
                name: float(value) for name, value in zip(mixed_unknown_names, mixed["normalized_mean_abs_error"])
            },
            "std_relative_error": {
                name: float(value) for name, value in zip(mixed_unknown_names, mixed["std_relative_error"])
            },
            "truth_rmse": {name: float(value) for name, value in zip(mixed_unknown_names, mixed["truth_rmse"])},
            "coverage_68": {name: float(value) for name, value in zip(mixed_unknown_names, mixed["coverage_68"])},
        },
    }


def run_validation(
    *,
    n_train: int = 8192,
    n_test: int = 16,
    n_reference: int = 50_000,
    epochs: int = 90,
    num_samples: int = 128,
    steps: int = 32,
    seed: int = 20260706,
    output_dir: str | Path = "outputs/diffusion_toy_sed_validation",
    model: str = "mlp",
    strict: bool = False,
    verbose: bool = False,
) -> dict:
    """Run the nonlinear toy-SED diffusion validation."""

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(seed)

    x_train, _, _ = make_training_table(rng, n_train)
    x_test, mags_test, theta_test = make_training_table(rng, n_test)
    reference_theta = sample_prior(rng, n_reference)
    reference_mags_noiseless = toy_noiseless_magnitudes(reference_theta)

    feature_names = BAND_NAMES + PARAM_NAMES
    metadata = FeatureMetadata.from_groups({"mags": BAND_NAMES, "params": PARAM_NAMES})
    if model == "hybrid_sed":
        model_config = {
            "emb_dim": 48,
            "time_hidden": 64,
            "cnn_channels": 32,
            "cnn_blocks": 1,
            "param_hidden": 64,
            "param_blocks": 1,
            "fusion_hidden": 64,
            "fusion_blocks": 2,
        }
    else:
        model_config = {
            "hidden_features": 96,
            "num_blocks": 3,
            "emb_dim": 64,
            "time_hidden": 96,
        }
    estimator = ConditionalDiffusionEstimator(
        metadata,
        model=model,
        hidden_features=96,
        model_config=model_config,
        sigma_min=0.02,
        sigma_max=2.0,
        learning_rate=2e-3,
        device="auto",
    )
    history = estimator.fit(
        x_train,
        mask_config={
            "curriculum": [
                {"weight": 1.0, "unknown_fraction": {"mags": 0.0, "params": 1.0}},
                {"weight": 1.0, "unknown_fraction": {"mags": 1.0, "params": 0.0}},
                {"weight": 1.0, "unknown_fraction": {"mags": [0.25, 0.5, 0.75], "params": [0.5, 1.0]}},
            ]
        },
        epochs=epochs,
        batch_size=1024,
        seed=seed,
        clamp_known_in_xt=True,
        loss_on_unknown_only=True,
        verbose=verbose,
    )

    all_mag_index = np.arange(len(BAND_NAMES))
    theta_index = np.arange(len(BAND_NAMES), len(feature_names))
    inverse_full, inverse_seconds, inverse_clamp = sample_diffusion_case(
        estimator,
        x_test,
        all_mag_index,
        num_samples=num_samples,
        steps=steps,
    )
    inverse_diffusion = inverse_full[:, :, theta_index]
    inverse_reference, inverse_ess = reference_inverse_samples(
        mags_test,
        reference_theta,
        reference_mags_noiseless,
        rng,
        n_samples=num_samples,
        band_index=all_mag_index,
    )
    inverse = compare_sample_cubes(inverse_diffusion, inverse_reference, theta_test)
    inverse["seconds"] = inverse_seconds
    inverse["known_max_abs_error"] = inverse_clamp

    forward = evaluate_forward_mags_given_theta(
        estimator,
        x_test,
        theta_test,
        num_samples=num_samples,
        steps=steps,
    )

    known_blue_index = np.array([0, 1, 2, 3], dtype=int)
    missing_red_index = np.array([4, 5, 6, 7], dtype=int)
    mixed_known_index = known_blue_index
    mixed_full, mixed_seconds, mixed_clamp = sample_diffusion_case(
        estimator,
        x_test,
        mixed_known_index,
        num_samples=num_samples,
        steps=steps,
    )
    mixed_unknown_index = np.concatenate([missing_red_index, theta_index])
    mixed_diffusion = mixed_full[:, :, mixed_unknown_index]
    mixed_reference, mixed_ess = reference_mixed_samples(
        mags_test,
        reference_theta,
        reference_mags_noiseless,
        rng,
        n_samples=num_samples,
        known_band_index=known_blue_index,
        missing_band_index=missing_red_index,
    )
    mixed_truth = np.column_stack([mags_test[:, missing_red_index], theta_test])
    mixed = compare_sample_cubes(mixed_diffusion, mixed_reference, mixed_truth)
    mixed["seconds"] = mixed_seconds
    mixed["known_max_abs_error"] = mixed_clamp
    mixed_unknown_names = [feature_names[i] for i in mixed_unknown_index]

    plot_training_loss(history, output_path)
    plot_inverse_summary(inverse, output_path)
    plot_forward_summary(forward, output_path)
    plot_mixed_summary(mixed, mixed_unknown_names, output_path)
    plot_toy_sed_example(mags_test[0], theta_test[0], inverse_diffusion, output_path)

    metrics = serializable_metrics(
        history=history,
        device=str(estimator.device),
        inverse=inverse,
        forward=forward,
        mixed=mixed,
        inverse_ess=inverse_ess,
        mixed_ess=mixed_ess,
        mixed_unknown_names=mixed_unknown_names,
    )
    metrics["model"] = str(model)
    metrics["n_train"] = int(n_train)
    metrics["n_test"] = int(n_test)
    metrics["n_reference"] = int(n_reference)
    metrics["num_samples"] = int(num_samples)
    metrics["steps"] = int(steps)
    metrics["strict"] = bool(strict)
    metrics["smoke_checks"] = {
        "finite_inverse_samples": bool(np.all(np.isfinite(inverse_diffusion))),
        "finite_mixed_samples": bool(np.all(np.isfinite(mixed_diffusion))),
        "known_coordinates_clamped": bool(max(inverse_clamp, forward["known_max_abs_error"], mixed_clamp) <= 1e-5),
        "inverse_reference_ess_ok": bool(np.median(inverse_ess) >= 25),
        "inverse_mean_error_ok": bool(np.mean(inverse["normalized_mean_abs_error"]) <= 2.0),
        "forward_mean_rmse_ok": bool(forward["mean_rmse"] <= 1.0),
    }
    metrics["inverse_theta_given_all_mags"]["seconds"] = float(inverse_seconds)
    metrics["inverse_theta_given_all_mags"]["known_max_abs_error"] = float(inverse_clamp)
    metrics["mixed_missing_red_bands"]["seconds"] = float(mixed_seconds)
    metrics["mixed_missing_red_bands"]["known_max_abs_error"] = float(mixed_clamp)

    with (output_path / "metrics.json").open("w", encoding="utf-8") as handle:
        json.dump(metrics, handle, indent=2)

    if max(inverse_clamp, forward["known_max_abs_error"], mixed_clamp) > 1e-5:
        raise RuntimeError("Known/clamped coordinates were not preserved exactly.")
    if not np.all(np.isfinite(inverse_diffusion)) or not np.all(np.isfinite(mixed_diffusion)):
        raise RuntimeError("Diffusion samples contain NaN or inf.")
    if strict:
        if np.median(inverse_ess) < 25:
            raise RuntimeError("Reference posterior ESS is too small; increase n_reference or noise.")
        if np.mean(inverse["normalized_mean_abs_error"]) > 2.0:
            raise RuntimeError("Inverse posterior differs too strongly from the brute-force reference.")
        if forward["mean_rmse"] > 1.0:
            raise RuntimeError("Forward sampled magnitudes are too far from the exact toy likelihood mean.")

    return metrics


def main() -> None:
    metrics = run_validation()
    print(json.dumps(metrics, indent=2))


if __name__ == "__main__":
    main()
